#!/usr/bin/env node
import { createInterface } from 'node:readline/promises';
import { execFileSync } from 'node:child_process';
import {
  existsSync,
  readdirSync,
  writeFileSync,
  rmSync,
  realpathSync,
} from 'node:fs';
import { resolve, basename } from 'node:path';
import { pathToFileURL } from 'node:url';
import { stdin, stdout, exit } from 'node:process';

const REPO = 'https://github.com/alagappan17/memory-soda.git';
const PG_IMAGE = 'pgvector/pgvector:pg16';
const PG_CONTAINER = 'memory-soda-pg';
const DOCKER_URL =
  'postgresql://memory_user:memory_pass@localhost:5432/memory_db';

const bold = (s) => `\x1b[1m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const yellow = (s) => `\x1b[33m${s}\x1b[0m`;

function die(msg) {
  console.error(`\n${yellow('✗')} ${msg}\n`);
  exit(1);
}

/** Run a command with its output attached to our stdio. Throws on non-zero. */
function run(cmd, args, opts = {}) {
  return execFileSync(cmd, args, { stdio: 'inherit', ...opts });
}

/** Run a command quietly, returning stdout — or null if it failed or is missing. */
function tryRun(cmd, args, opts = {}) {
  try {
    return execFileSync(cmd, args, { encoding: 'utf8', stdio: 'pipe', ...opts });
  } catch {
    return null;
  }
}

/**
 * Render the .env file. Only the values the installer collects are written
 * explicitly — everything else stays on the defaults baked into config.ts, so
 * this file does not drift every time a new option is added there.
 */
export function renderEnv({ databaseUrl, geminiKey, adminUser, adminPassword }) {
  const lines = [
    '# Generated by create-memory-soda.',
    '# Full reference: https://github.com/alagappan17/memory-soda',
    '',
    '# PostgreSQL — must have the pgvector extension available.',
    `DATABASE_URL=${databaseUrl}`,
    '',
    '# Google Gemini — get a key at https://aistudio.google.com',
    `GOOGLE_GENERATIVE_AI_API_KEY=${geminiKey}`,
    '',
    '# Dashboard login, created once on first boot.',
    `ADMIN_USERNAME=${adminUser}`,
  ];
  // An unset ADMIN_PASSWORD makes the API generate one and print it once. That
  // is a better default than writing a weak chosen password to disk, so a blank
  // answer omits the key entirely rather than writing an empty one.
  if (adminPassword) lines.push(`ADMIN_PASSWORD=${adminPassword}`);
  lines.push('', '# Web', 'NEXT_PUBLIC_API_URL=http://localhost:3004', '');
  return lines.join('\n');
}

/** True if the path is safe to scaffold into: missing, or an empty directory. */
export function isUsableTarget(dir) {
  if (!existsSync(dir)) return true;
  return readdirSync(dir).filter((f) => f !== '.DS_Store').length === 0;
}

async function main() {
  if (Number(process.versions.node.split('.')[0]) < 20) {
    die(`Node 20 or newer is required — you are on ${process.versions.node}.`);
  }
  if (!tryRun('git', ['--version'])) die('git is required but was not found.');

  console.log(`\n${bold('memory-soda')} — self-hosted memory for AI agents\n`);

  // Read answers off the line iterator rather than rl.question(): with a piped
  // stdin, question() consumes only the first line of a buffered chunk and
  // drops the rest, so `printf 'a\nb\n' | npm create memory-soda` would stall.
  const rl = createInterface({ input: stdin });
  const lines = rl[Symbol.asyncIterator]();
  const ask = async (q, fallback = '') => {
    const hint = fallback ? ` ${dim(`(${fallback})`)}` : '';
    stdout.write(`${q}${hint}: `);
    const { value, done } = await lines.next();
    // EOF (a script that piped fewer answers than there are questions) takes
    // the default rather than hanging.
    if (done) stdout.write('\n');
    return (value ?? '').trim() || fallback;
  };

  const dirName = process.argv[2] || (await ask('Folder name', 'memory-soda'));
  const target = resolve(process.cwd(), dirName);
  if (!isUsableTarget(target)) {
    rl.close();
    die(`${target} already exists and is not empty.`);
  }

  const geminiKey = await ask('Gemini API key');
  if (!geminiKey) {
    console.log(dim('  No key given — set it in .env before starting.'));
  }

  const useDocker =
    (await ask('Postgres: [d]ocker or [e]xisting instance?', 'd'))
      .toLowerCase()
      .startsWith('d');

  let databaseUrl = DOCKER_URL;
  if (useDocker) {
    if (!tryRun('docker', ['--version'])) {
      rl.close();
      die('Docker was not found. Re-run and choose [e] to use your own Postgres.');
    }
  } else {
    databaseUrl = await ask(
      'DATABASE_URL',
      'postgresql://localhost:5432/memory_db',
    );
  }

  const adminUser = await ask('Dashboard admin username', 'admin');
  const adminPassword = await ask(
    `Dashboard admin password ${dim('(blank = generate one)')}`,
  );
  rl.close();

  console.log(`\n${bold('→')} Cloning into ${dirName}`);
  run('git', ['clone', '--depth', '1', REPO, target]);
  rmSync(resolve(target, '.git'), { recursive: true, force: true });

  writeFileSync(
    resolve(target, '.env'),
    renderEnv({ databaseUrl, geminiKey, adminUser, adminPassword }),
  );
  console.log(`${bold('→')} Wrote .env`);

  if (useDocker) {
    console.log(`${bold('→')} Starting Postgres (${PG_CONTAINER})`);
    // Reuse the container across re-runs: a named container that already exists
    // holds the user's data, so recreating it would silently wipe their memory.
    const existing = tryRun('docker', [
      'ps', '-aq', '--filter', `name=^${PG_CONTAINER}$`,
    ]);
    if (existing && existing.trim()) {
      run('docker', ['start', PG_CONTAINER]);
      console.log(dim(`  Reused the existing ${PG_CONTAINER} container.`));
    } else {
      run('docker', [
        'run', '-d',
        '--name', PG_CONTAINER,
        '-e', 'POSTGRES_USER=memory_user',
        '-e', 'POSTGRES_PASSWORD=memory_pass',
        '-e', 'POSTGRES_DB=memory_db',
        '-p', '5432:5432',
        PG_IMAGE,
      ]);
    }
  } else {
    const probe = tryRun('psql', [
      '-d', databaseUrl, '-tAc',
      "SELECT 1 FROM pg_available_extensions WHERE name = 'vector'",
    ]);
    if (probe === null) {
      console.log(
        dim('  Could not verify pgvector (psql missing or connection failed).'),
      );
    } else if (!probe.trim()) {
      console.log(
        `${yellow('!')} pgvector is not available on that database — install it before starting.`,
      );
    }
  }

  console.log(`${bold('→')} Installing dependencies ${dim('(this takes a minute)')}`);
  run('npm', ['install'], { cwd: target });

  console.log(`\n${green('✓')} ${bold(basename(target))} is ready.\n`);
  console.log(`  cd ${dirName}`);
  console.log(`  npm run dev\n`);
  console.log(dim('  First boot applies migrations and prints your API key once.'));
  console.log(dim(`  Dashboard http://localhost:3000 · API http://localhost:3004`));
  console.log(
    dim(
      adminPassword
        ? `  Log in as ${adminUser} with the password you chose.\n`
        : `  Log in as ${adminUser} — the generated password is printed at first boot.\n`,
    ),
  );
}

/**
 * True when this file is the process entry point, false when it is imported.
 *
 * argv[1] must be resolved through realpath first: npm and npx invoke the bin
 * as a symlink in `node_modules/.bin`, while `import.meta.url` is already the
 * real path — comparing them raw makes every installed run a no-op.
 */
function isEntryPoint() {
  if (!process.argv[1]) return false;
  try {
    return import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href;
  } catch {
    return false;
  }
}

// Importing this file (tests) must not start an interactive session.
if (isEntryPoint()) {
  main().catch((err) => die(err.message));
}
