#!/usr/bin/env node
import { spawn, execFileSync } from 'node:child_process';
import { existsSync, readdirSync, writeFileSync, rmSync, realpathSync } from 'node:fs';
import { resolve, basename, join } from 'node:path';
import { createRequire } from 'node:module';
import { connect } from 'node:net';
import { exit } from 'node:process';
import { pathToFileURL } from 'node:url';
import * as p from '@clack/prompts';
import chalk from 'chalk';

const REPO = 'https://github.com/alagappan17/memory-soda.git';
const DEFAULT_DB = 'postgresql://localhost:5432/memory_db';
const VERBOSE = process.argv.includes('--verbose');

function die(msg) {
  console.error(`\n${chalk.red('✗')} ${msg}\n`);
  exit(1);
}

/** Bail if the user hit ctrl-c on a prompt. */
function guard(value) {
  if (p.isCancel(value)) die('Cancelled.');
  return value;
}

/** Run a command quietly, returning stdout — or null if it failed or is missing. */
function tryRun(cmd, args, opts = {}) {
  try {
    return execFileSync(cmd, args, { encoding: 'utf8', stdio: 'pipe', ...opts });
  } catch {
    return null;
  }
}

/**
 * Run a long command behind a spinner. The spinner shows the command's last
 * output line as it goes; the full log only appears if it fails (or with
 * --verbose, where it streams straight through).
 */
function runWithSpinner(title, cmd, args, { cwd } = {}) {
  if (VERBOSE) {
    p.log.step(title);
    return new Promise((done, fail) => {
      spawn(cmd, args, { cwd, stdio: 'inherit' }).on('close', (code) =>
        code === 0 ? done() : fail(new Error(`${cmd} exited with ${code}`)),
      );
    });
  }
  const s = p.spinner();
  s.start(title);
  return new Promise((done, fail) => {
    let log = '';
    const child = spawn(cmd, args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] });
    const onData = (chunk) => {
      log += chunk;
      const last = String(chunk).trim().split('\n').pop()?.trim();
      if (last) s.message(`${title} ${chalk.dim(last.slice(0, 60))}`);
    };
    child.stdout.on('data', onData);
    child.stderr.on('data', onData);
    child.on('close', (code) => {
      if (code === 0) return s.stop(title) ?? done();
      s.stop(`${title} — failed`, 1);
      p.log.error(log.trim().split('\n').slice(-20).join('\n'));
      fail(new Error(`${cmd} ${args.join(' ')} exited with ${code}. Re-run with --verbose for the full log.`));
    });
  });
}

/**
 * Render the .env file. Only the values the installer collects are written
 * explicitly — everything else stays on the defaults baked into config.ts, so
 * this file does not drift every time a new option is added there.
 */
export function renderEnv({ databaseUrl, geminiKey, adminUser, adminPassword, apiPort, dashboardPort }) {
  const lines = [
    '# Generated by create-memory-soda.',
    '# Full reference: https://github.com/alagappan17/memory-soda',
    '',
    '# PostgreSQL — must have the pgvector extension available.',
    `DATABASE_URL=${databaseUrl}`,
    '',
    '# Google Gemini — REQUIRED for extraction and search. Get a key at https://aistudio.google.com',
    `GOOGLE_GENERATIVE_AI_API_KEY=${geminiKey}`,
    '',
    '# Ports. CORS_ORIGIN must match where the dashboard is served from, and',
    "# VITE_API_URL is the browser's view of the API — not the server's.",
    `PORT=${apiPort}`,
    `DASHBOARD_PORT=${dashboardPort}`,
    `CORS_ORIGIN=http://localhost:${dashboardPort}`,
    `VITE_API_URL=http://localhost:${apiPort}`,
    '',
    '# Dashboard login, created once on first boot.',
    `ADMIN_USERNAME=${adminUser}`,
  ];
  // An unset ADMIN_PASSWORD makes the API generate one and print it once. That
  // is a better default than writing a weak chosen password to disk, so a blank
  // answer omits the key entirely rather than writing an empty one.
  if (adminPassword) lines.push(`ADMIN_PASSWORD=${adminPassword}`);
  lines.push('');
  return lines.join('\n');
}

/** True if the path is safe to scaffold into: missing, or an empty directory. */
export function isUsableTarget(dir) {
  if (!existsSync(dir)) return true;
  return readdirSync(dir).filter((f) => f !== '.DS_Store').length === 0;
}

/**
 * Pull the host and port out of a Postgres connection string, for the cheap
 * reachability probe. Returns null for anything unparseable.
 */
export function parsePostgresUrl(url) {
  try {
    const u = new URL(url);
    if (!u.protocol.startsWith('postgres')) return null;
    return { host: u.hostname || 'localhost', port: Number(u.port) || 5432 };
  } catch {
    return null;
  }
}

/** Is something accepting TCP connections there? Cheap pre-flight, 2s budget. */
function isReachable({ host, port }, timeout = 2000) {
  return new Promise((done) => {
    const socket = connect({ host, port });
    const finish = (result) => {
      socket.destroy();
      done(result);
    };
    socket.setTimeout(timeout);
    socket.once('connect', () => finish(true));
    socket.once('timeout', () => finish(false));
    socket.once('error', () => finish(false));
  });
}

function loadPg(target) {
  const require = createRequire(pathToFileURL(join(target, 'package.json')));
  return require('pg').Client;
}

/** Create the database named in the URL by connecting to the maintenance db on the same server. */
async function createDatabase(target, databaseUrl) {
  const Client = loadPg(target);
  const url = new URL(databaseUrl);
  const db = decodeURIComponent(url.pathname.slice(1));
  url.pathname = '/postgres';
  const client = new Client({ connectionString: url.href });
  try {
    await client.connect();
    await client.query(`CREATE DATABASE "${db.replaceAll('"', '""')}"`);
  } finally {
    await client.end().catch(() => {});
  }
}

/**
 * Connect for real and confirm pgvector is installable, using the `pg` copy
 * inside the freshly installed project so the installer needs no database
 * driver of its own. Returns null on success, or an operator-readable problem.
 */
export async function checkDatabase(target, databaseUrl) {
  let Client;
  try {
    Client = loadPg(target);
  } catch {
    return { skipped: 'could not load pg from the new project' };
  }

  const client = new Client({ connectionString: databaseUrl });
  try {
    await client.connect();
    const { rows } = await client.query("SELECT 1 FROM pg_available_extensions WHERE name = 'vector'");
    if (rows.length === 0) {
      return {
        problem: 'pgvector is not available on this server',
        fix: 'Install it — brew install pgvector, or apt install postgresql-16-pgvector — then retry.',
      };
    }
    return null;
  } catch (err) {
    if (err.code === '3D000') {
      const db = decodeURIComponent(new URL(databaseUrl).pathname.slice(1));
      return { problem: `database "${db}" does not exist`, fix: `createdb ${db}`, missingDb: db };
    }
    if (err.code === '28P01' || err.code === '28000') {
      return { problem: 'authentication failed', fix: 'Check the user and password in the URL.' };
    }
    if (err.code === 'ECONNREFUSED') {
      return {
        problem: 'nothing is accepting connections at that host and port',
        fix: 'Start Postgres — brew services start postgresql, or pg_ctl start.',
      };
    }
    return { problem: err.message, fix: null };
  } finally {
    await client.end().catch(() => {});
  }
}

const validPort = (v) => {
  if (!v) return; // blank takes the default
  const n = Number(v);
  if (!Number.isInteger(n) || n < 1 || n > 65535) return 'Enter a port between 1 and 65535.';
};

async function main() {
  if (Number(process.versions.node.split('.')[0]) < 20) {
    die(`Node 20 or newer is required — you are on ${process.versions.node}.`);
  }
  if (!tryRun('git', ['--version'])) die('git is required but was not found.');

  console.log();
  p.intro(`${chalk.bgCyan.black(' Memory Soda ')} ${chalk.dim('self-hosted memory for AI agents')}`);

  const dirArg = process.argv.slice(2).find((a) => !a.startsWith('-'));
  const dirName =
    dirArg ||
    guard(
      await p.text({
        message: 'Where should we create your project?',
        placeholder: 'memory-soda',
        defaultValue: 'memory-soda',
        validate: (v) =>
          isUsableTarget(resolve(process.cwd(), v || 'memory-soda')) ? undefined : 'That folder exists and is not empty.',
      }),
    );
  const target = resolve(process.cwd(), dirName);
  if (!isUsableTarget(target)) die(`${target} already exists and is not empty.`);

  const geminiKey = guard(
    await p.password({
      message: `Gemini API key ${chalk.dim('(aistudio.google.com — required for the memory layer, leave blank to add to .env later)')}`,
      mask: '•',
    }),
  ) ?? '';
  if (!geminiKey) p.log.warn('No key given. Memory extraction and search will not work until GOOGLE_GENERATIVE_AI_API_KEY is set in .env.');

  let databaseUrl = guard(
    await p.text({
      message: `Postgres URL ${chalk.dim('(bring your own — pgvector must be installed; the database itself is created for you)')}`,
      placeholder: DEFAULT_DB,
      defaultValue: DEFAULT_DB,
      validate: (v) => (v && !parsePostgresUrl(v) ? 'Expected a postgres:// URL.' : undefined),
    }),
  );
  const addr = parsePostgresUrl(databaseUrl);
  if (addr && !(await isReachable(addr))) {
    // Only a warning: the server may legitimately be starting, or firewalled
    // from here but reachable from wherever the app will actually run.
    p.log.warn(`Nothing is listening on ${addr.host}:${addr.port} right now — checked again after install.`);
  }

  const apiPort = Number(guard(await p.text({ message: 'API port', placeholder: '3004', defaultValue: '3004', validate: validPort })));
  const dashboardPort = Number(
    guard(await p.text({ message: 'Dashboard port', placeholder: '3000', defaultValue: '3000', validate: validPort })),
  );
  const adminUser = guard(await p.text({ message: 'Dashboard admin username', placeholder: 'admin', defaultValue: 'admin' }));
  const adminPassword =
    guard(await p.password({ message: `Dashboard admin password ${chalk.dim('(leave blank to generate one at first boot)')}`, mask: '•' })) ?? '';

  await runWithSpinner(`Cloning into ${chalk.bold(dirName)}`, 'git', ['clone', '--depth', '1', REPO, target]);
  rmSync(resolve(target, '.git'), { recursive: true, force: true });

  const writeEnv = () =>
    writeFileSync(resolve(target, '.env'), renderEnv({ databaseUrl, geminiKey, adminUser, adminPassword, apiPort, dashboardPort }));
  writeEnv();
  p.log.success('Wrote .env');

  await runWithSpinner('Installing dependencies', 'npm', ['ci', '--no-audit', '--no-fund'], { cwd: target });

  // Now that pg exists in the project, check the database for real. Looping
  // here beats failing at first boot: the fix is usually one command away and
  // the answer is still in front of the user.
  for (;;) {
    const s = p.spinner();
    s.start('Checking the database');
    let result = await checkDatabase(target, databaseUrl);
    if (result?.missingDb) {
      s.message(`Creating database ${result.missingDb}`);
      try {
        await createDatabase(target, databaseUrl);
        result = await checkDatabase(target, databaseUrl);
      } catch (err) {
        result = { problem: `could not create database "${result.missingDb}": ${err.message}`, fix: result.fix };
      }
    }
    if (result === null) {
      s.stop('Database ready — connected, pgvector available');
      break;
    }
    if (result.skipped) {
      s.stop(`Database check skipped — ${result.skipped}`, 1);
      break;
    }
    s.stop(`Database: ${result.problem}`, 1);
    if (result.fix) p.log.info(result.fix);
    const retry = guard(
      await p.text({
        message: 'Fix it and press enter to retry, paste a new DATABASE_URL, or type s to skip',
        placeholder: 'enter to retry',
      }),
    ) ?? '';
    if (retry.toLowerCase() === 's') {
      p.log.warn('Skipped — the API will fail on boot until this is resolved.');
      break;
    }
    if (retry) {
      databaseUrl = retry;
      writeEnv();
    }
  }

  p.note(
    [
      `cd ${dirName}`,
      'npm run dev',
      '',
      `Dashboard  ${chalk.underline(`http://localhost:${dashboardPort}`)}`,
      `API        ${chalk.underline(`http://localhost:${apiPort}`)}`,
      `Login      ${adminUser} / ${adminPassword ? 'the password you chose' : 'password printed at first boot'}`,
      '',
      'First boot applies migrations and prints your API key once.',
      ...(geminiKey ? [] : ['Set GOOGLE_GENERATIVE_AI_API_KEY in .env before starting.']),
    ].join('\n'),
    'Next steps',
  );
  p.outro(`${chalk.bold(basename(target))} is ready.`);
}

/**
 * True when this file is the process entry point, false when it is imported.
 * argv[1] is resolved through realpath: npm and npx invoke the bin as a
 * symlink in node_modules/.bin, while import.meta.url is the real path.
 */
function isEntryPoint() {
  if (!process.argv[1]) return false;
  try {
    return import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href;
  } catch {
    return false;
  }
}

// Importing this file (tests) must not start an interactive session.
if (isEntryPoint()) {
  main().catch((err) => die(err.message));
}
